### ISSUE TITLE
Gateway test raises error out of the box.

### ISSUE THREAD

**Issue by ryaan-anthony** [workarea-commerce/workarea-emarsys#1]
Workarea Version: 3.4

```Error:
Workarea::Emarsys::GatewayTest#test_create_contact:
NoMethodError: undefined method `utc' for nil:NilClass
    

/workarea/docker/bundle/gems/escher-1.0.2/lib/escher/auth.rb:266:in `long_date'
/workarea/docker/bundle/gems/escher-1.0.2/lib/escher/auth.rb:206:in `format_date_for_header'
/workarea/docker/bundle/gems/escher-1.0.2/lib/escher/auth.rb:25:in `sign!'
/workarea/docker/bundle/gems/workarea-emarsys-1.0.1/app/lib/workarea/emarsys/gateway.rb:55:in `sign_request'
/workarea/docker/bundle/gems/workarea-emarsys-1.0.1/app/lib/workarea/emarsys/gateway.rb:19:in `create_contact'
/workarea/docker/bundle/gems/workarea-emarsys-1.0.1/test/lib/workarea/emarsys/gateway_test.rb:19:in `block in test_create_contact'
/workarea/docker/bundle/gems/vcr-2.9.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
/workarea/docker/bundle/gems/vcr-2.9.3/lib/vcr.rb:182:in `use_cassette'
/workarea/docker/bundle/gems/workarea-emarsys-1.0.1/test/lib/workarea/emarsys/gateway_test.rb:17:in `test_create_contact'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest/test.rb:107:in `block (3 levels) in run'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest/test.rb:204:in `capture_exceptions'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest/test.rb:104:in `block (2 levels) in run'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest/test.rb:255:in `time_it'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest/test.rb:103:in `block in run'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest.rb:350:in `on_signal'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest/test.rb:275:in `with_info_handler'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest/test.rb:102:in `run'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest.rb:839:in `run_one_method'
/workarea/docker/bundle/gems/minitest-retry-0.1.9/lib/minitest/retry.rb:77:in `block in run_one_method'
/workarea/docker/bundle/gems/minitest-retry-0.1.9/lib/minitest/retry.rb:69:in `times'
/workarea/docker/bundle/gems/minitest-retry-0.1.9/lib/minitest/retry.rb:69:in `run_one_method'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest.rb:324:in `run_one_method'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest.rb:311:in `block (2 levels) in run'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest.rb:310:in `each'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest.rb:310:in `block in run'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest.rb:350:in `on_signal'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest.rb:337:in `with_info_handler'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest.rb:309:in `run'
/workarea/docker/bundle/gems/railties-5.2.3/lib/rails/test_unit/line_filtering.rb:10:in `run'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest.rb:159:in `block in __run'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest.rb:159:in `map'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest.rb:159:in `__run'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest.rb:136:in `run'
/workarea/docker/bundle/gems/minitest-5.10.3/lib/minitest.rb:63:in `block in autorun'```

**Comment by tubbo** [comment]
This is also fixed by #2
